
version: '3'

services:
  # Flask application service
  flask-app:
    build: .
    ports:
      - "5000:5000"  # Flask app
      - "8000:8000"  # Prometheus metrics
    networks:
      - monitoring

  # Prometheus service
  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9092:9090"
    networks:
      - monitoring

  # Grafana service
  grafana:
    image: grafana/grafana:9.0.3
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Default admin password
    ports:
      - "3001:3000"
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge
